blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/gautammanak1/uagent-client/discussions
    about: Ask questions and discuss ideas
  - name: 📚 Documentation
    url: https://github.com/gautammanak1/uagent-client#readme
    about: Check the README for documentation
  - name: 🔒 Security Vulnerability
    url: https://github.com/gautammanak1/uagent-client/security/advisories/new
    about: Report security vulnerabilities (please use Security Advisory)

